/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package prac2task2;
import prac2task2.Reader;

public class App {
    public static void main(String[] args) {
        Reader reader = new Reader();
        String path = "C:/Users/Sello Prince Lebudi/Desktop/Prac2Task2/Prac2.xml";
        reader.readAndPrint(path);
    }
}
